### ISSUE TITLE
Tabs not loading css in 3.0

### ISSUE THREAD

**Issue by arnoudwarschauer** [HardeepAsrani/advanced-css-editor#12]
![schermafbeelding 2018-10-21 om 15 32 52](https://user-images.githubusercontent.com/24248768/47267610-9dff9580-d546-11e8-9656-d14c2c2c2217.png)

Bug:
Tab's not working after the update to 3.0 
You can click them but the view from global will remain...

Question: How can I extract the css from the editor? I would like to make a backup of the styles :)

I am using Wordpress 4.8.7.

**Comment by HardeepAsrani** [comment]
Hey there,

Sorry I never got a notification for this. Are you still using the plugin and having this issue?
